### ISSUE TITLE
Fix travis configuration

### ISSUE THREAD

**Issue by markusguenther** [breadlesscode/neos-blog#12]
### Description

The automated release is broken at the moment. The travis backend uses an invalid GitHub token.
So @breadlesscode needs to configure a new GitHub token.

### Steps to Reproduce

1. Commit something and watch travis log ;)

#### Expected behavior

Travis is able to create tags on GitHub.

#### Actual behavior

![bildschirmfoto 2019-01-16 um 21 16 11](https://user-images.githubusercontent.com/1014126/51276192-53ba7300-19d4-11e9-9a46-982c32c862af.png)

**Comment by breadlesscode** [comment]
Done thanks :)

**Comment by markusguenther** [comment]
👍🏼
