### ISSUE TITLE
Suggestion: Author page

### ISSUE THREAD

**Issue by jonnitto** [breadlesscode/neos-blog#5]
It would be nice to have an author page where I can add some information about the writer.

- Image of the author
- Social links (e. g. Twitter)
- Teaser of the posts the author has written (E. g. https://www.smashingmagazine.com/author/rachel-andrew/)
- Some personal text about the author
- A short brief which will be shown on every post of the author (e. g. https://www.smashingmagazine.com/2018/09/flexbox-sizing-flexible-box)

**Comment by markusguenther** [comment]
Yeah sounds good :)
