### ISSUE TITLE
Use translated date format

### ISSUE THREAD

**Issue by Benjamin-K** [breadlesscode/neos-blog#6]
Instead of using `Date.format` you can use `Date.formatCldr(theDate, 'E, dd. MMMM y H:mm:ss (zzzz)')` to get a translated date for the posts. 

See https://github.com/breadlesscode/neos-blog/blob/72d11093f307b690d44b89cf687a49bdba87d992/Resources/Private/Fusion/Document/Post.fusion#L30.

**Comment by markusguenther** [comment]
Thank you for the nice feedback. We will take care of it soonish. If you want feel free to submit a PR :)
